### ISSUE TITLE
Exception in native call     java.lang.IndexOutOfBoundsException: index=1 count=0

### ISSUE THREAD

**Issue by TrustTheBoy** [Microsoft/react-native-code-push#1020]
### Can it be reproduced in Demo: NO.
> When you update and restart, App returns to the desktop and opens manually again. The content has not changed and the update is prompted for the latest version
## error mess
```java
Exception in native call
    java.lang.IndexOutOfBoundsException: index=1 count=0
    at android.view.ViewGroup.addInArray(ViewGroup.java:4303)
    at android.view.ViewGroup.addViewInner(ViewGroup.java:4234)
    at android.view.ViewGroup.addView(ViewGroup.java:4065)
    at android.view.ViewGroup.addView(ViewGroup.java:4010)
    at com.facebook.react.uimanager.ViewGroupManager.addView(ViewGroupManager.java:47)
    at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:395)
    at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:179)
    at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:768)
    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:824)
    at com.facebook.react.uimanager.UIViewOperationQueue.access$1600(UIViewOperationQueue.java:48)
    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:870)
    at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
    at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
    at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:775)
    at android.view.Choreographer.doCallbacks(Choreographer.java:590)
    at android.view.Choreographer.doFrame(Choreographer.java:559)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:5942)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
09-27 19:46:38.957 28212-28212/com.mobilegovernment D/ReactNative: [CodePush] Update did not finish loading the last time, rolling back to a previous version.
09-27 19:46:38.967 28212-31246/com.mobilegovernment W/unknown:React: The packager does not seem to be running as we got an IOException requesting its status: Unable to resolve host "6": No address associated with hostname
09-27 19:46:39.037 28212-28212/com.mobilegovernment E/unknown:React: Tried to remove non-existent frame callback
09-27 19:46:39.037 28212-28212/com.mobilegovernment W/unknown:React: Not flushing pending UI operations because of previously thrown Exception
09-27 19:46:39.047 28212-28212/com.mobilegovernment W/unknown:React: Packager connection already open, nooping.
09-27 19:46:39.047 28212-28212/com.mobilegovernment W/unknown:React: Inspector connection already open, nooping.
09-27 19:46:39.057 28212-28272/com.mobilegovernment W/ContextImpl: Failed to ensure directory: /storage/extSdCard/Android/data/com.mobilegovernment/cache
09-27 19:46:39.067 28212-31247/com.mobilegovernment D/React:  View manager getCommandsMap:
09-27 19:46:39.077 28212-28212/com.mobilegovernment D/AbsListView: Get MotionRecognitionManager
09-27 19:46:39.087 28212-28212/com.mobilegovernment V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xhdpi-v4/spinner_white_16.png
09-27 19:46:39.087 28212-28273/com.mobilegovernment W/ContextImpl: Failed to ensure directory: /storage/extSdCard/Android/data/com.mobilegovernment/cache
09-27 19:46:39.137 28212-31247/com.mobilegovernment E/unknown:React: Exception in native call
com.facebook.jni.CppException: facebook::react::Recoverable: Could not open file/data/data/com.mobilegovernment/files/CodePush/ff893de120cea6fe6f83aada868ff56a082fb71db07cb7c329df9a81d38e51e7/CodePush/index.android.bundle: No such file or directory
    at com.facebook.react.cxxbridge.CatalystInstanceImpl.jniLoadScriptFromFile(Native Method)
    at com.facebook.react.cxxbridge.CatalystInstanceImpl.loadScriptFromFile(CatalystInstanceImpl.java:203)
    at com.facebook.react.cxxbridge.JSBundleLoader$2.loadScript(JSBundleLoader.java:53)
    at com.facebook.react.cxxbridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:216)
    at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:994)
    at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109)
    at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:746)
    at java.lang.Thread.run(Thread.java:818)
09-27 19:46:39.307 28212-28212/com.mobilegovernment I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@3aefb1ed time:181821499
09-27 19:46:53.057 28212-28212/com.mobilegovernment D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
09-27 19:46:53.237 28212-28301/com.mobilegovernment E/unknown:React: Could not open stack frame
java.net.UnknownHostException: Unable to resolve host "6": No address associated with hostname
    at java.net.InetAddress.lookupHostByName(InetAddress.java:427)
    at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
    at java.net.InetAddress.getAllByName(InetAddress.java:215)
    at okhttp3.Dns$1.lookup(Dns.java:39)
    at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:172)
    at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:138)
    at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:80)
    at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:178)
    at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
    at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
    at okhttp3.RealCall.execute(RealCall.java:60)
    at com.facebook.react.devsupport.RedBoxDialog$OpenStackFrameTask.doInBackground(RedBoxDialog.java:214)
    at com.facebook.react.devsupport.RedBoxDialog$OpenStackFrameTask.doInBackground(RedBoxDialog.java:191)
    at android.os.AsyncTask$2.call(AsyncTask.java:288)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by TrustTheBoy** [comment]
@max-mironov @sergey-akhalkov  help!!!

**Comment by max-mironov** [comment]
@TrustTheBoy your issue is looking similar to this one: https://github.com/Microsoft/react-native-code-push/issues/921
It was fixed in PR https://github.com/Microsoft/react-native-code-push/pull/924 and released in [RNCP 4.1.0-beta,](https://github.com/Microsoft/react-native-code-push/releases/tag/v4.1.0-beta) so could you please update to this version and let us know if you still can see the issue?

**Comment by TrustTheBoy** [comment]
@max-mironov 
hank you, I haven't had this problem since the update, but new problems have come up,
When I download the update, the phone will not automatically restart the update, manual execution of codepush.syn, App will restart, how can I solve this problem?

**Comment by TrustTheBoy** [comment]
@max-mironov Again, the 3.0.1 error occurred

**Comment by max-mironov** [comment]
@TrustTheBoy can you share the minimum example how you integrate code push?
Also do I get it right that updating to the latest React-Native and react-native-code-push didn't solve your problem?

**Comment by TrustTheBoy** [comment]
@max-mironov Yes, not resolved. I have updated react/react-native to the corresponding version of RNCP
```javascript
import CodePush from 'react-native-code-push';
import { Toast, WhiteSpace, WingBlank, Button, Icon } from 'antd-mobile';

const options = {
    updateDialog: {
        appendReleaseDescription: true,
        descriptionPrefix: '更新内容：\n',
        title: '更新标题',
        mandatoryUpdateMessage: '',
        optionalUpdateMessage: '',
        mandatoryContinueButtonLabel: '立即更新',
        optionalInstallButtonLabel: '立即安装',
        optionalIgnoreButtonLabel: '取消更新',
    },
    mandatoryInstallMode: CodePush.InstallMode.IMMEDIATE,
};

export const CodePushUpdate = () => {
    CodePush.allowRestart();
    // CodePush.disallowRestart();
    CodePush.sync(
        options,
        (syncStatus) => {
            Toast.loading(syncStatusChangeCallback(syncStatus), 1, () => {
                console.log('Load complete !!!');
            });
        },
        progress => syncStatusChangeCallback(progress),
        RemotePackage => alert('ppppppp'),
    );
};
const downloadProgressCallback = (progress) => {
    console.log('downloadProgressCallback');
    console.log(progress);
};
const handleBinaryVersionMismatchCallback = (RemotePackage) => {
    console.log('handleBinaryVersionMismatchCallback');
    console.log(RemotePackage);
};
export const syncStatusChangeCallback = (syncStatus) => {
    let ToastMess = '';
    switch (syncStatus) {
    case CodePush.SyncStatus.CHECKING_FOR_UPDATE:
        ToastMess = '正在检查更新。';
        break;
    case CodePush.SyncStatus.DOWNLOADING_PACKAGE:
        ToastMess = '正在下载更新包';
        break;
    case CodePush.SyncStatus.AWAITING_USER_ACTION:
        ToastMess = '等待用户操作';
        break;
    case CodePush.SyncStatus.INSTALLING_UPDATE:
        ToastMess = 'Installing update.';
        break;
    case CodePush.SyncStatus.UP_TO_DATE:
        ToastMess = 'App 已是最新版本';
        break;
    case CodePush.SyncStatus.UPDATE_IGNORED:
        ToastMess = '用户取消更新.';
        break;
    case CodePush.SyncStatus.UPDATE_INSTALLED:
        ToastMess = '更新安装并将用于重新启动.';
        break;
    case CodePush.SyncStatus.UNKNOWN_ERROR:
        ToastMess = '发生未知错误,请及时联系管理员.';
        break;
    default:
        ToastMess = 'default';
    }
    return ToastMess;
};

```
and Update in time

```javascript
componentDidMount() {
        this.onLoadingData();
        CodePush.allowRestart();
        AppState.addEventListener('change', (newState) => {
            newState === 'active' && CodePushUpdate();
        });
    }
```

**Comment by TrustTheBoy** [comment]
@max-mironov I tried 20 times, and this error caused App to start: "appName no response", followed by withdrawal, and the probability of error is 6/20;

**Comment by TrustTheBoy** [comment]
@max-mironov "App does not respond" is due to an update restart that will cause OOM 
```
09-27 21:22:07.978 2667-2685/com.mobilegovernment W/EGL_emulation: eglSurfaceAttrib not implemented
09-27 21:22:07.978 2667-2685/com.mobilegovernment W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xd1029660, error=EGL_SUCCESS
09-27 21:22:14.020 2667-2685/com.mobilegovernment D/OpenGLRenderer: endAllStagingAnimators on 0xd5f08780 (RippleDrawable) with handle 0xd3904cb0
09-27 21:22:15.422 2667-9509/com.mobilegovernment D/ReactNative: [CodePush] Loading JS bundle from "/data/data/com.mobilegovernment/files/CodePush/0199781d7af639d5c9df34a1319634259bdf994d0b92f5a906facb77dc7833e9/CodePush/index.android.bundle"
09-27 21:22:15.485 2667-2682/com.mobilegovernment I/art: Clamp target GC heap from 108MB to 96MB
09-27 21:22:15.525 2667-11579/com.mobilegovernment W/unknown:React: The packager does not seem to be running as we got an IOException requesting its status: Unable to resolve host "0": No address associated with hostname
09-27 21:22:15.624 2667-2667/com.mobilegovernment W/unknown:React: Packager connection already open, nooping.
09-27 21:22:15.625 2667-2667/com.mobilegovernment W/unknown:React: Inspector connection already open, nooping.
09-27 21:22:15.646 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupViewManager
09-27 21:22:15.646 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
09-27 21:22:15.646 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeViewManager
09-27 21:22:15.646 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
09-27 21:22:15.647 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextViewManager
09-27 21:22:15.647 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
09-27 21:22:15.647 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
09-27 21:22:15.648 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
09-27 21:22:15.651 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
09-27 21:22:15.652 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
09-27 21:22:15.652 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
09-27 21:22:15.655 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
09-27 21:22:15.656 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
09-27 21:22:15.657 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
09-27 21:22:15.659 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
09-27 21:22:15.659 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
09-27 21:22:15.659 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
09-27 21:22:15.660 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
09-27 21:22:15.660 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
09-27 21:22:15.661 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
09-27 21:22:15.662 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
09-27 21:22:15.663 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
09-27 21:22:15.663 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
09-27 21:22:15.663 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
09-27 21:22:15.663 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
09-27 21:22:15.664 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
09-27 21:22:15.668 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
09-27 21:22:15.668 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
09-27 21:22:15.668 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
09-27 21:22:15.669 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
09-27 21:22:15.670 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
09-27 21:22:15.672 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
09-27 21:22:15.672 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
09-27 21:22:15.672 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
09-27 21:22:15.673 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
09-27 21:22:15.673 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
09-27 21:22:15.673 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.github.alinz.reactnativewebviewbridge.WebViewBridgeManager
09-27 21:22:15.674 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class org.wonday.pdf.RCTPdfManager
09-27 21:22:15.675 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.lottie.LottieAnimationViewManager
09-27 21:22:15.677 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.cmcewen.blurview.BlurViewManager
09-27 21:22:15.679 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.react_native_signature.RCTSignatureManager
09-27 21:22:15.680 2667-11580/com.mobilegovernment D/React:  View manager getCommandsMap:
09-27 21:22:15.680 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.rssignaturecapture.RSSignatureCaptureViewManager
09-27 21:22:15.681 2667-11580/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.lwansbrough.RCTCamera.RCTCameraViewManager
09-27 21:22:16.155 2667-2667/com.mobilegovernment I/Choreographer: Skipped 30 frames!  The application may be doing too much work on its main thread.
09-27 21:22:16.155 2667-2667/com.mobilegovernment W/unknown:React: Packager connection already open, nooping.
09-27 21:22:16.155 2667-2667/com.mobilegovernment W/unknown:React: Inspector connection already open, nooping.
09-27 21:22:16.329 2667-11585/com.mobilegovernment E/BluetoothAdapter: Bluetooth binder is null
09-27 21:22:16.458 2667-2892/com.mobilegovernment I/art: Alloc sticky concurrent mark sweep GC freed 48826(2MB) AllocSpace objects, 5(80KB) LOS objects, 3% free, 92MB/96MB, paused 35.623ms total 56.250ms
09-27 21:22:16.526 2667-2892/com.mobilegovernment I/art: Clamp target GC heap from 108MB to 96MB
09-27 21:22:16.543 2667-2892/com.mobilegovernment I/art: Alloc partial concurrent mark sweep GC freed 9213(453KB) AllocSpace objects, 1(36KB) LOS objects, 3% free, 92MB/96MB, paused 5.108ms total 59.808ms
09-27 21:22:16.608 2667-2677/com.mobilegovernment W/art: Suspending all threads took: 8.799ms
09-27 21:22:16.610 2667-2892/com.mobilegovernment I/art: Clamp target GC heap from 108MB to 96MB
09-27 21:22:16.611 2667-2892/com.mobilegovernment I/art: Alloc concurrent mark sweep GC freed 2859(132KB) AllocSpace objects, 0(0B) LOS objects, 3% free, 92MB/96MB, paused 1.636ms total 44.375ms
09-27 21:22:16.613 2667-2892/com.mobilegovernment I/art: Forcing collection of SoftReferences for 10MB allocation
09-27 21:22:16.640 2667-2892/com.mobilegovernment I/art: Clamp target GC heap from 108MB to 96MB
09-27 21:22:16.640 2667-2892/com.mobilegovernment I/art: Alloc concurrent mark sweep GC freed 1815(91KB) AllocSpace objects, 0(0B) LOS objects, 4% free, 92MB/96MB, paused 690us total 26.874ms
09-27 21:22:16.644 2667-2892/com.mobilegovernment E/art: Throwing OutOfMemoryError "Failed to allocate a 10969356 byte allocation with 4037260 free bytes and 3MB until OOM"
09-27 21:22:16.663 2667-2892/com.mobilegovernment I/art: Clamp target GC heap from 106MB to 96MB
09-27 21:22:16.663 2667-2892/com.mobilegovernment I/art: Alloc partial concurrent mark sweep GC freed 30446(1880KB) AllocSpace objects, 0(0B) LOS objects, 5% free, 90MB/96MB, paused 718us total 14.120ms
09-27 21:22:16.679 2667-2892/com.mobilegovernment I/art: Clamp target GC heap from 106MB to 96MB
09-27 21:22:16.679 2667-2892/com.mobilegovernment I/art: Alloc concurrent mark sweep GC freed 6(176B) AllocSpace objects, 0(0B) LOS objects, 5% free, 90MB/96MB, paused 780us total 14.543ms
09-27 21:22:16.681 2667-2892/com.mobilegovernment I/art: Forcing collection of SoftReferences for 10MB allocation
09-27 21:22:16.718 2667-2892/com.mobilegovernment I/art: Clamp target GC heap from 106MB to 96MB
09-27 21:22:16.718 2667-2892/com.mobilegovernment I/art: Alloc concurrent mark sweep GC freed 6(112B) AllocSpace objects, 0(0B) LOS objects, 5% free, 90MB/96MB, paused 921us total 36.224ms
09-27 21:22:16.733 2667-2892/com.mobilegovernment E/art: Throwing OutOfMemoryError "Failed to allocate a 10969356 byte allocation with 5963028 free bytes and 5MB until OOM"
                                                         
                                                         --------- beginning of crash
09-27 21:22:17.068 2667-2892/com.mobilegovernment E/AndroidRuntime: FATAL EXCEPTION: Thread-338
        Process: com.mobilegovernment, PID: 2667
        java.lang.OutOfMemoryError: Failed to allocate a 10969356 byte allocation with 5963028 free bytes and 5MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.Bitmap.nativeCreate(Native Method)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
        at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:55)
        at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:30)
        at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
        at com.facebook.imagepipeline.platform.ArtDecoder.decodeStaticImageFromStream(ArtDecoder.java:137)
        at com.facebook.imagepipeline.platform.ArtDecoder.decodeFromEncodedImage(ArtDecoder.java:81)
        at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeStaticImage(DefaultImageDecoder.java:158)
        at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:71)
        at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:123)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:239)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:111)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:144)
        at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
        at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
        at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
        at java.lang.Thread.run(Thread.java:818)
09-27 21:22:17.106 2667-11616/com.mobilegovernment W/unknown:ReconnectingWebSocket: Couldn't connect to "ws://0/message?device=Samsung%20Galaxy%20S6%20-%205.1.0%20-%20API%2022%20-%201440x2560&app=com.mobilegovernment&clientid=DevSupportManagerImpl", will silently retry
09-27 21:22:17.110 2667-11617/com.mobilegovernment W/unknown:InspectorPackagerConnection: Couldn't connect to packager, will silently retry
09-27 21:22:18.512 2667-11586/com.mobilegovernment W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
09-27 21:22:19.119 2667-2682/com.mobilegovernment W/art: Suspending all threads took: 9.534ms
09-27 21:22:19.138 2667-2677/com.mobilegovernment W/art: Suspending all threads took: 15.702ms
09-27 21:22:19.153 2667-2682/com.mobilegovernment I/art: Background sticky concurrent mark sweep GC freed 37466(1506KB) AllocSpace objects, 12(192KB) LOS objects, 1% free, 94MB/96MB, paused 10.660ms total 53.115ms
09-27 21:22:20.055 2667-2682/com.mobilegovernment I/art: Clamp target GC heap from 107MB to 96MB

```

**Comment by max-mironov** [comment]
@TrustTheBoy thanks for getting back!

**Comment by WhoJave** [comment]
@TrustTheBoy  hi , how do you solved this crash on Samsung ? I  use react-native-pushy and just crash on Samsung , could u do me a favor ? Tks so much

**Comment by xinghuoliaoyuan45** [comment]
me too

**Comment by mcmar** [comment]
@TrustTheBoy Can you share what/how you refactored that may have fixed this issue? I'm using the latest version of RNCP and still getting this

**Comment by flutterq** [comment]
[[Solved] IllegalStateException: function = , count = 3, index = 3 in Android
](https://exerror.com/solved-illegalstateexception-function-count-3-index-3-in-android/)
