### ISSUE TITLE
Dependency failing: com.nimbusds:nimbus-jose-jwt:5.1 -> net.minidev:json-smart@[1.3.1,2.3]

### ISSUE THREAD

**Issue by afilp** [microsoft/react-native-code-push#1448]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
When trying to run our Android project (react-native), this fails.

### Expected Behavior
What you expected to happen?

The Android app to be compiled.

### Actual Behavior
What actually happens?

The compilation of our react-native app (Android) fails quite early, by throwing this error message:

```
  Dependency failing: com.nimbusds:nimbus-jose-jwt:5.1 -> net.minidev:json-smart@[1.3.1,2.3], but json-smart version was 2
  .3.
  
  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends on project 'react' which depends onto com.nimbusds:nimbus-jose-jwt@5.1

```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: ^5.4.2
* react-native version: 16.6,1
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @afilp ,
Thanks for reporting!

It is strange issue. Could you please provide some dummy project with reproducing issue? I would like to debug it.

Thanks,
Alexander

**Comment by afilp** [comment]
@alexandergoncharov Thanks for your fast reply, the project I am using is rather complicated to make it simpler and submit it here. 

I can say for sure that the problem arises when we are using `apply plugin: 'com.google.gms.google-services'` in order to support the `react-native-firebase`. (as explained in their installation doc here: https://rnfirebase.io/docs/v5.x.x/installation/android )

Something is used there related to `net.minidev:json-smart` that conflicts with your use of `net.minidev:json-smart` (in versioning).

**Comment by afilp** [comment]
Hello, I am not sure what else to do, as I am not entitled to send the private project here.

Is there a `resolution` setting I could use?

I am not sure what this message means:

`Dependency failing: com.nimbusds:nimbus-jose-jwt:5.1 -> net.minidev:json-smart@[1.3.1,2.3], but json-smart version was 2.3.`

**Comment by alexandergoncharov** [comment]
Hi @afilp ,
Sorry for delay.

It is strange issue as I have also `com.nimbusds:nimbus-jose-jwt:5.1` and `net.minidev:json-smart:2.3` in my dummy project and all works correct.
Could you please share your `android/app/build/intermediates/transforms/dexBuilder/debug/__content__.json` file, `build.gradle` file from root folder and `app/build.gradle` file?
I would like to reproduce your issue and investigate it.

**Comment by AndrewJack** [comment]
@alexandergoncharov 

The issue occurs when using v4.2.0 of the google-services plugin.
E.g. 
```gradle
classpath 'com.google.gms:google-services:4.2.0'
```

Downgrading to v4.1.0 works around this issue temporarily.

**Comment by afilp** [comment]
Please see here, the following seems to have worked!
https://github.com/invertase/react-native-firebase/issues/1676

**Comment by AlMel3000** [comment]
> Please see here, the following seems to have worked!
> [invertase/react-native-firebase#1676](https://github.com/invertase/react-native-firebase/issues/1676)

try to add

`com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true`

at the bottom of android/app/build.gradle

**Comment by alexandergoncharov** [comment]
Hi @AlMel3000 , @AndrewJack , thanks for providing workarounds.

I reproduced issue. My investigation in progress.

**Comment by doniwinata0309** [comment]
Hi @alexandergoncharov  any update on this issue ? i guess we have to use google service 4.2.0 on Android Gradle Plugin 3.3, or we will got runtime error (it happened on my project):
https://stackoverflow.com/questions/52374463/googleservice-failed-to-initialize-status-10-missing-google-app-id-value-from/54200175#54200175
Thanks !

**Comment by janakg** [comment]
Any resolution for this issue? I confirm the problem.

**Comment by melihberberolu** [comment]
Any solution ?

**Comment by zachgibb** [comment]
I think this may be due to an issue with the version checker itself: https://github.com/google/play-services-plugins/issues/30

The error itself is kind of confusing in the first place. It's saying the resolved version `2.3` isn't compatible with the version required `[1.3.1,2.3]`. From what I've looked up, the square bracket syntax is supposed to be an inclusive range meaning `[from_version, to_version]` - meaning that having the version resolve to `2.3` should be supported, as the acceptable range is **up to and including** `2.3`.

However, the version checker at the moment is essentially saying
```
if (there are square brackets) {
  make sure the string within the brackets _exactly_ matches the resolved version
} else {
  any versions are compatible
}
```
Which is a bit odd, since we'd only use those square brackets when we would have **two** versions to compare between - so any use of `[from_version, to_version]` would throw an error. Unless of course, you used the brackets to indicate only one version `[version]`, which is completely unnecessary.

Given that the only instance that the version checker _is actually doing its job_ is broken right now, I think it should be safe to disable the version check like @AlMel3000 said:
```
com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
```

Until a fix drops for https://github.com/google/play-services-plugins/issues/30, I'm not sure there's any other solution - or honestly any benefit to using that version checker in the first place.

**Comment by l3ender** [comment]
If the version checker has a bug, could a hotfix with it disabled be merged and released until the upstream fix is in place?

**Comment by moret** [comment]
Instead of disabling the version check, I temporarily forced the removal of `json-smart` from `react-native-code-push` dependency:

```gradle
    implementation(project(':react-native-code-push')){
        exclude group: 'net.minidev:json-smart'
    }
```

I'm still looking out for any side effects though.

**Comment by junejosheeraz** [comment]
It hit me today with following while running simple build on my project;

    [ERROR] Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.2.2:package (package-azure-functions) on project ms-holdings-package-azure: Execution package-azure-functions of goal com.microsoft.azure:azure-functions-maven-plugin:1.2.2:package failed: Plugin com.microsoft.azure:azure-functions-maven-plugin:1.2.2 or one of its dependencies could not be resolved: Failed to collect dependencies at com.microsoft.azure:azure-functions-maven-plugin:jar:1.2.2 -> com.microsoft.azure:azure-maven-plugin-lib:jar:1.2.7 -> com.microsoft.azure:azure:jar:1.17.1 -> com.microsoft.azure:azure-client-authentication:jar:1.6.3 -> com.microsoft.azure:adal4j:jar:1.6.2 -> com.nimbusds:oauth2-oidc-sdk:jar:5.64.4 -> net.minidev:json-smart:jar:[1.3.1,2.3]: No versions available for net.minidev:json-smart:jar:[1.3.1,2.3] within specified range -> [Help 1]

    Azure maven Plugin Version Tried: 1.3.0, 1.3.1, 1.2.2 

It was working fine previously, somehow maven is trying to resolve [1.3.1,2.3] of net.minidev as is instead of ranges it seems. I have verified and library is available with these version on maven central. 

Anyone else found a workaround!

**Comment by BachirKhiati** [comment]
You can solve this problem by adding this to your "app/build.gradle" dependencies :

> dependencies
>  {
>         components.all {
>         allVariants {
>             withDependencies { deps ->
>                 deps.each { dep ->
>                     if (dep.group == 'net.minidev' && dep.name =='json-smart') {
>                         dep.version {
>                             prefer "2.3"
>                         }
>                         dep.because "resolving dependencies issue"
>                     }
>                 }
>             }
>         }
>     }
>    ..... other dependencies
>  }
> 

Since I know that my project works with version 2.3, using component metadata project you can ignore whatever version other components want (you take the responsibility).

**Comment by jonas-arkulpa** [comment]
@BachirKhiati 
Thx for this solution. It is a lot more specific than just disabling the version check all together. 👍
Unfortunately it somehow doesn't work if I select `Rebuild Project` from the `Build` menu.
No clue why this behaves differently than a normal gradle sync.

**Comment by vinicarra** [comment]
@jonas-arkulpa would you mind to share your `build.gradle` content here? I've tried the above solution yet I've not manage to make it work here, perhaps I'm missing something...

**Comment by jonas-arkulpa** [comment]
@vincentfretin Unfortunately I can't provide you more information about this project.
But I basically copy pasted @BachirKhiati's solution and the sync worked as expected.

**Comment by vincentfretin** [comment]
@jonas-arkulpa  I have nothing to do with this issue. :) I think you meant to mention @vinicarra

**Comment by pallaviMN** [comment]
@BachirKhiati , can you please post your entire gradle file, i am unable to run it after copy pasting your solution

**Comment by levani** [comment]
I'm having the same issue after updating to react native 0.59.

**Comment by BachirKhiati** [comment]
@jonas-arkulpa, @pallaviMN 
Did you invalidate the cache in Android studio after you did the changes? That should solve the problem.

**Comment by uyend** [comment]
This solution worked for me. 

If you have included `implementation project(':react-native-code-push')` and you are definitely importing this dependency from another project then you can exclude this dependency in the react-native-code-push project. 

Modify this line to your build.gradle in the react-native-code-push project. 

`compile 'com.nimbusds:nimbus-jose-jwt:5.1'` -> 
`compile('com.nimbusds:nimbus-jose-jwt:5.1') {
        exclude group: "net.minidev", module: "json-smart"
    }'

**Comment by vivek-walecha-657** [comment]
> Hi @AlMel3000 , @AndrewJack , thanks for providing workarounds.
> 
> I reproduced issue. My investigation in progress.

Hi, Have you got any workaround?

**Comment by vivek-walecha-657** [comment]
> I think this may be due to an issue with the version checker itself: [google/play-services-plugins#30](https://github.com/google/play-services-plugins/issues/30)
> 
> The error is kind of confusing in the first place. It's saying the resolved version `2.3` isn't compatible with the version required `[1.3.1,2.3]`. The square bracket syntax is supposed to be an inclusive range meaning `[from_version, to_version]` - so having the version resolve to `2.3` should be supported, as the acceptable range is **up to and including** `2.3`.
> 
> However, the version checker at the moment is essentially saying
> 
> ```
> if (there are square brackets) {
>   make sure the string within the brackets _exactly_ matches the resolved version
> } else {
>   any versions are compatible
> }
> ```
> 
> Which is a bit odd, since we'd only use those square brackets when we would have **two** versions to compare between - so any use of `[from_version, to_version]` would throw an error. Unless of course, you used the brackets to indicate only one version `[version]`, which is completely unnecessary.
> 
> Given that the only instance that the version checker _is actually doing its job_ is broken right now, I think it should be safe to disable the version check like @AlMel3000 said:
> 
> ```
> com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
> ```
> 
> Until a fix drops for [google/play-services-plugins#30](https://github.com/google/play-services-plugins/issues/30), I'm not sure there's any other solution - or honestly any benefit to using that version checker in the first place.
> 
> _(disclaimer, this is only from recent research after digging into this error)_

I also investigated this from my end.

**Comment by ruipaulo** [comment]
Is there any chance that this is addressed soon? All proposed solutions boil down to mess with the build process to ignore version mismatches. This may be a solution for building, but might lead to runtime crashes. For me this is a really serious issue, as having code-push and firebase in one project seems to be a typical use case for many react-native apps.

**Comment by vivek-walecha-657** [comment]
@ruipaulo yeah you are absolutely correct.

**Comment by brian-perlego** [comment]
Any update on this?

**Comment by MrLoh** [comment]
@alexandergoncharov would be great if the team could fix this.

**Comment by andercard** [comment]
We are waiting for this

**Comment by mi-mazouz** [comment]
+1

**Comment by Subway19** [comment]
+1

Having an issue with react native 0.59.10

**Comment by faridsaud** [comment]
+1

Nothing worked for me!

**Comment by prebhas** [comment]
Having an issue with react native 0.59.9

**Comment by Lawrence93Ho** [comment]
downgrading the distributionUrl in gradle-wrapper.properties worked for me:
from ```distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip```
to```distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip```

**Comment by MinaFSedrak** [comment]
@BachirKhiati your solution doesn't work using latest gradle version 3.4.1, any update !?

**Comment by MrLoh** [comment]
@alexandergoncharov any update on a solution for this?

**Comment by BachirKhiati** [comment]
> @BachirKhiati your solution doesn't work using latest gradle distributionUrl=https://services.gradle.org/distributions/
> any update !?

@MinaFSedrak , I was able to successfully compile and run my project with the 
`distributionUrl=https://services.gradle.org/distributions/gradle-5.4.1-all.zip` 
Same setup as in my previous post + adding at the bottom of android/app/build.gradle :
`com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
`

**Comment by SudoPlz** [comment]
@BachirKhiati couldn't this lead in runtime errors ^

**Comment by rezasazesh** [comment]
+1

Nothing worked for me!

**Comment by ruipaulo** [comment]
What's going on with codepush? No answers on this urgent issue for month? Microsoft used to be super responsive on GH ....? I start considering to drop CodePush/AppCenter.

**Comment by rezasazesh** [comment]
I made it work by adding `com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true` at the bottom of android/app/build.gradle. I also have `multiDexEnabled true` inside defaultConfig -> android -> android/app/build.gradle

downgrading `classpath 'com.google.gms:google-services:4.2.0'` to `4.1.0` makes the build however causes issues with Firebase

I have not experienced problems in runtime for now. I believe this is a temporary fix only anyways and MS should fix this

**Comment by ahmedamirss** [comment]
Any update on the issue?

**Comment by tuananhluong** [comment]
May be help for who still face this issue: refer from https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/37

> Starting with com.google.gms:google-services:4.3.0 you must now instead add the following to the bottom of your app/build.gradle, after the apply.

`googleServices { disableVersionCheck = true }`

My version is: classpath 'com.google.gms:google-services:4.3.2'

**Comment by joan-saum** [comment]
This solution has been proposed in this issue.
It's working yes but this should be a temporary fix, we expect a real fix but it seems this library is deprecated. No information, no support from Microsoft since months...

**Comment by mikehardy** [comment]
@joan-saum this repository is alive but they're doing a bit of work under the covers I *think* to enable things like delta bundles etc. They have been responsive enough in that they confirm it does work on current react-native in one of the issues, and I've seen them active in other venues. So don't write the repo off ;-)

That said, this issue is not their fault. It's a problem with the google-services plugin, it has a PR that is unmerged but could maybe use community support / commentary to raise profile? https://github.com/google/play-services-plugins/pull/95

**Comment by huang-ju** [comment]
```
Duplicate class net.jcip.annotations.GuardedBy found in modules jcip-annotations-1.0-1.jar (com.github.stephenc.jcip:jcip-annotations:1.0-1) and jcip-annotations-1.0.jar (net.jcip:jcip-annotations:1.0)
Duplicate class net.jcip.annotations.Immutable found in modules jcip-annotations-1.0-1.jar (com.github.stephenc.jcip:jcip-annotations:1.0-1) and jcip-annotations-1.0.jar (net.jcip:jcip-annotations:1.0)
Duplicate class net.jcip.annotations.NotThreadSafe found in modules jcip-annotations-1.0-1.jar (com.github.stephenc.jcip:jcip-annotations:1.0-1) and jcip-annotations-1.0.jar (net.jcip:jcip-annotations:1.0)
Duplicate class net.jcip.annotations.ThreadSafe found in modules jcip-annotations-1.0-1.jar (com.github.stephenc.jcip:jcip-annotations:1.0-1) and jcip-annotations-1.0.jar (net.jcip:jcip-annotations:1.0)

Go to the documentation to learn how to Fix dependency resolution errors.
```

This error occurs with implementation 'com.nimbusds:nimbus-jose-jwt:5.1'

**Comment by craigcoles** [comment]
I was experiencing the same issue: 

```
Dependency failing: com.nimbusds:nimbus-jose-jwt:5.1 -> net.minidev:json-smart@[1.3.1,2.3], but json-smart version was 2
  .3.
  
  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends on project 'react' which depends onto net.minidev:json-smart@{strictly 2.3}
  -- Project 'app' depends on project 'react' which depends onto com.nimbusds:nimbus-jose-jwt@{strictly 5.1}
  -- Project 'app' depends on project 'react' which depends onto com.nimbusds:nimbus-jose-jwt@5.1
```

I was see this after upgrading `com.google.gms:google-services` from version `4.1.0` to `4.2.0`. However, this issue is no longer happening after upgrading to the current latest version `4.3.3`.

**Comment by ThanhNghia944** [comment]
Fixed 
apply plugin: 'com.google.gms.google-services'
googleServices {
    disableVersionCheck = true
}

**Comment by mikehardy** [comment]
> Fixed
> apply plugin: 'com.google.gms.google-services'
> googleServices {
> disableVersionCheck = true
> }

With the new plug in version this should no longer be necessary

**Comment by callmejm** [comment]
changing google service version to 4.3.3 , the issue is gone, however it will mess up react-native-firebase

**Comment by mikehardy** [comment]
@callmejm false assertion, google services version 4.3.3 works wonderfully with react-native-firebase

**Comment by Krasavinigor** [comment]
Hi all! 
Codepush works correctly with google services version 4.3.3 and fixes this issue. Does anyone have any issues?

**Comment by Krasavinigor** [comment]
I'm going to close this issue if you have any questions or other issues, feel free to reopen it.

**Comment by meliodev** [comment]
Hello, codepush was working properly until I started getting this error today with:
google-services 4.3.3
gradle 3.5.3
react-native-code-push 7.0.2

**Comment by zwang62** [comment]
@mikehardy   I got this problem again without any change today. It has been running well before.
google-services 4.3.3
gradle 3.5.3
react-native-code-push 7.0.1

**Comment by aamir-ans** [comment]
> Hello, codepush was working properly until I started getting this error today with:
> google-services 4.3.3
> gradle 3.5.3
> react-native-code-push 7.0.2

+1

**Comment by letrinhthanhvn** [comment]
> @mikehardy I got this problem again without any change today. It has been running well before.
> google-services 4.3.3
> gradle 3.5.3
> react-native-code-push 7.0.1

+1

**Comment by meliodev** [comment]
Maybe JCenter is down again ?? https://status.jitpack.io/

Check out this:
https://github.com/react-native-camera/react-native-camera/issues/2490

**Comment by alexandergoncharov** [comment]
https://status.jitpack.io/ is back to `Operational`.

Could you please double-check if you still have issues with this?

**Comment by superhero2007** [comment]
classpath("com.android.tools.build:gradle:4.1.0")
        classpath 'com.google.gms:google-services:4.3.4'
        "react-native-code-push": "^7.0.0",
        
        This is not working for me.

**Comment by hiepns97it** [comment]
thank-you <3.  @`uyend`

**Comment by congnguyen91** [comment]
Gradle is down today :v

**Comment by bonnmh** [comment]
@congnguyen91  how do i know when it will be fixed

**Comment by bonnmh** [comment]
> > Gradle is down today :v
> 
> Their [status website](https://status.gradle.com/) seems to show that it's operational, yet I'm still getting the error.

I also had the same problem, it worked fine in the past days

**Comment by ferasabufares** [comment]
+1 same here 
Not working 
i try all the solution but none of them are working with me 

can you please give me a solution

**Comment by BhargaviOS** [comment]
+1 same here
Getting error like below

```Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve net.minidev:json-smart:[1.3.1,2.3].
     Required by:
         project :app > project :react-native-code-push > com.nimbusds:nimbus-jose-jwt:5.1
      > Failed to list versions for net.minidev:json-smart.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml'.
               > org.apache.http.client.ClientProtocolException (no error message)```

**Comment by kamal-j** [comment]
+1
`FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve net.minidev:json-smart:[1.3.1,2.3].
     Required by:
         project :app > project :react-native-code-push > com.nimbusds:nimbus-jose-jwt:5.1
      > Failed to list versions for net.minidev:json-smart.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml'.
               > org.apache.http.client.ClientProtocolException (no error message)`

**Comment by hiepns97it** [comment]
I fixed it by changing in react-native-code-push
node-module/react-native-code-push/android/app/build.gradle
edit line implementation('com.nimbusds:nimbus-jose-jwt:5.1') to implementation('com.nimbusds:nimbus-jose-jwt:5.1') { exclude group: "net.minidev", module: "json-smart" }

**Comment by congnguyen91** [comment]
I fix by add mavenCentral
<img width="575" alt="Screen Shot 2022-05-09 at 12 12 38" src="https://user-images.githubusercontent.com/18322684/167359743-05ef9d69-3c50-461d-9509-fb457b3184a1.png">

**Comment by MKmurali241** [comment]
@hiepns97it  Please can share the code

**Comment by bansalakshay8** [comment]
> I fix by add mavenCentral <img alt="Screen Shot 2022-05-09 at 12 12 38" width="575" src="https://user-images.githubusercontent.com/18322684/167359743-05ef9d69-3c50-461d-9509-fb457b3184a1.png">

Thanks @congnguyen91  it worked. But do you think installing gradle dependencies from 3 different repo(jcenter,mavenLocal,mavenCentral), will impact any of the things?

**Comment by MKmurali241** [comment]
Thanks @congnguyen91  it worked.

**Comment by congnguyen91** [comment]
@bansalakshay8 This impacts timing of the build (maybe dependent on your network performance) a few of minutes - not the app's run time performance. But build successfully is better than error, let's be priority for devs.

**Comment by gattigaga** [comment]
> I fix by add mavenCentral <img alt="Screen Shot 2022-05-09 at 12 12 38" width="575" src="https://user-images.githubusercontent.com/18322684/167359743-05ef9d69-3c50-461d-9509-fb457b3184a1.png">

Hi, @congnguyen91...
Could you share the full content of that build.gradle file ?

Mine still failed to compile even I already put mavenCentral()...

**Comment by congnguyen91** [comment]
Here you are  @gattigaga
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        firebaseMessagingVersion = "21.1.0"
        googlePlayServicesVersion   = "16.0.0"
        googlePlayServicesVisionVersion = "18.0.0"
        googlePlayServicesBase      = "16.0.1"
        supportLibVersion   = "28.0.0"
        kotlinVersion = "1.3.61"
        RNNKotlinVersion = kotlinVersion
    }
    repositories {
        google()
        mavenLocal()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
        classpath 'com.android.tools.build:gradle:4.0.2'
        classpath 'com.google.gms:google-services:4.3.4'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenLocal()
        mavenCentral()
        jcenter()

        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        // maven { url 'https://jitpack.io' }
        maven { url 'https://www.jitpack.io' }
        // maven { url "https://maven.google.com" } 
    }
}
```

**Comment by gattigaga** [comment]
> 

@congnguyen91 Thank you... :D

**Comment by congnguyen91** [comment]
> I fixed it by changing in react-native-code-push node-module/react-native-code-push/android/app/build.gradle edit line implementation('com.nimbusds:nimbus-jose-jwt:5.1') to implementation('com.nimbusds:nimbus-jose-jwt:5.1') { exclude group: "net.minidev", module: "json-smart" }

This will make your app built successfully but It contains the potential crash. This is only used if lib duplicated.

**Comment by ferasabufares** [comment]
> mavenCentral()

thanks a lot <3
it is working

**Comment by imhikmat** [comment]
> I fix by add mavenCentral <img alt="Screen Shot 2022-05-09 at 12 12 38" width="575" src="https://user-images.githubusercontent.com/18322684/167359743-05ef9d69-3c50-461d-9509-fb457b3184a1.png">

It's working for me, thanks

**Comment by hmphu** [comment]
+1 same problem. I tried https://status.jitpack.io/ but it's not working

**Comment by BradleyGyemi-Qlik** [comment]
+1 same problem but ours is failing on version 5.7

Could not resolve net.minidev:json-smart:[1.3.1,2.3].
Required by:
    project : > com.nimbusds:nimbus-jose-jwt:5.7
      > Failed to list versions for net.minidev:json-smart.

**Comment by A9K5** [comment]
> Gradle is down today :v

@congnguyen91 Where can we verify/check this ?
coz acc. to [Gradle Status](https://status.gradle.com/#:~:text=No%20incidents%20reported%20today.) all is good !!

**Comment by increase21** [comment]
> I fixed it by changing in react-native-code-push node-module/react-native-code-push/android/app/build.gradle edit line implementation('com.nimbusds:nimbus-jose-jwt:5.1') to implementation('com.nimbusds:nimbus-jose-jwt:5.1') { exclude group: "net.minidev", module: "json-smart" }

**Comment by azrst** [comment]
> > I fixed it by changing in react-native-code-push node-module/react-native-code-push/android/app/build.gradle edit line implementation('com.nimbusds:nimbus-jose-jwt:5.1') to implementation('com.nimbusds:nimbus-jose-jwt:5.1') { exclude group: "net.minidev", module: "json-smart" }
> 
> This may make your app built successfully but It contains the potential crash. This is only used if lib duplicated but different lib versions.

thankss a lot, you saving my live :)

**Comment by sdrigues** [comment]
> I fixed it by changing in react-native-code-push node-module/react-native-code-push/android/app/build.gradle edit line implementation('com.nimbusds:nimbus-jose-jwt:5.1') to implementation('com.nimbusds:nimbus-jose-jwt:5.1') { exclude group: "net.minidev", module: "json-smart" }

Works for me

**Comment by Nirav1432** [comment]
> I fix by add mavenCentral <img alt="Screen Shot 2022-05-09 at 12 12 38" width="575" src="https://user-images.githubusercontent.com/18322684/167359743-05ef9d69-3c50-461d-9509-fb457b3184a1.png">

You saved my day, THanks @congnguyen91

**Comment by ksielyov** [comment]
> I fix by add mavenCentral <img alt="Screen Shot 2022-05-09 at 12 12 38" width="575" src="https://user-images.githubusercontent.com/18322684/167359743-05ef9d69-3c50-461d-9509-fb457b3184a1.png">

Man, You saved my life! Thank you!

**Comment by trinaygangisetty** [comment]
@sdrigues can we change the code in node modules? I mean for react-native-code-push package?

**Comment by PartypayNL** [comment]
Adding mavenCentral() fixed it for us.

**Comment by myan-soft-dev-reactnative** [comment]
> I fixed it by changing in react-native-code-push node-module/react-native-code-push/android/app/build.gradle edit line implementation('com.nimbusds:nimbus-jose-jwt:5.1') to implementation('com.nimbusds:nimbus-jose-jwt:5.1') { exclude group: "net.minidev", module: "json-smart" }

that work, thanks!
