### ISSUE TITLE
Could not determine the dependencies of task ':app:generateBundledResourcesHashOnlineBetaRelease'

### ISSUE THREAD

**Issue by LsFern** [microsoft/react-native-code-push#1613]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

When I did the packaging, I encountered the following problems
![TIM截图20190618115123](https://user-images.githubusercontent.com/32630118/59652286-b00e0280-91bf-11e9-806b-3ca8690c3665.png)

I tried to add this, but I still got an error
![TIM截图20190618115430](https://user-images.githubusercontent.com/32630118/59652321-dcc21a00-91bf-11e9-8236-c7c4d0a2bd55.png)

### Environment

* react-native-code-push version:5.1.3-beta
* react-native version:0.52.2
* gradle version:3.3.1

Does this reproduce on a debug build or release build? Release build. Debug build works fine.

**Comment by yuri-kulikov** [comment]
Hey @LsFern,
Thanks for reporting!

Please check [this](https://github.com/microsoft/react-native-code-push/issues/1427#issuecomment-430913598) out. This may be related to your issue (`react-native 0.52.2 + gradle 3.3.1`). Let me know if it's related or not 🙂

**Comment by LsFern** [comment]
I tried to change the gradle version to 3.1.3 and the gradle version to 4.4，but I still reported an error
![改gradle版本](https://user-images.githubusercontent.com/32630118/59730895-a4c9de00-9276-11e9-852d-9042a468a82e.png)

**Comment by LsFern** [comment]
@yuri-kulikov change the gradle version does not solve the problem

**Comment by LsFern** [comment]
@yuri-kulikov Changing the React-Native version to 0.57.8 can be packaged normally

**Comment by yuri-kulikov** [comment]
@LsFern, this is actually an external issue, this error simply indicates that something went wrong with react-native bundling process due to the gradle incompatibility.

Please let me know if you still have any questions!

**Comment by yuri-kulikov** [comment]
@LsFern I'll close the issue for now, but if you need any help or have any further questions feel free to ask or reopen the issue if needed.

Thanks for using CodePush!

**Comment by stueynet** [comment]
Hi there. I got the same thing only after installing react-native-code-push. Are we sure it's an external issue? We are using react native version `0.61.5`. Though my error message is slightly differen:

```
Could not determine the dependencies of task ':react-native-code-push:compileReleaseAidl'.
```

**Comment by LucasGarcez** [comment]
> Hi there. I got the same thing only after installing react-native-code-push. Are we sure it's an external issue? We are using react native version `0.61.5`. Though my error message is slightly differen:
> 
> ```
> Could not determine the dependencies of task ':react-native-code-push:compileReleaseAidl'.
> ```

I have the same problem with react-native version 0.61.5. [This solution in issue #1448  work for me](https://github.com/microsoft/react-native-code-push/issues/1448#issuecomment-561130291).

Update `com.google.gms:google-services` to version `4.3.3`, sync gradle and build again.

**Comment by callmejm** [comment]
> > Hi there. I got the same thing only after installing react-native-code-push. Are we sure it's an external issue? We are using react native version `0.61.5`. Though my error message is slightly differen:
> > ```
> > Could not determine the dependencies of task ':react-native-code-push:compileReleaseAidl'.
> > ```
> 
> I have the same problem with react-native version 0.61.5. [This solution in issue #1448 work for me](https://github.com/microsoft/react-native-code-push/issues/1448#issuecomment-561130291).
> 
> Update `com.google.gms:google-services` to version `4.3.3`, sync gradle and build again.

@LucasGarcez Hi, your solution fixed the issue, however if the project have install react-native-firebase, changing the google service version will mess up the entire build

**Comment by AbanoubAshraaf** [comment]
I fix by add mavenCentral
<img width="575" alt="167359743-05ef9d69-3c50-461d-9509-fb457b3184a1" src="https://user-images.githubusercontent.com/47993303/167887526-9afa2105-7f56-43ae-a587-37bc1e7cb275.png">

**Comment by trehman82** [comment]
> I fix by add mavenCentral <img alt="167359743-05ef9d69-3c50-461d-9509-fb457b3184a1" width="575" src="https://user-images.githubusercontent.com/47993303/167887526-9afa2105-7f56-43ae-a587-37bc1e7cb275.png">

fixed.......... thanks

**Comment by shahzaib14944** [comment]
@AbanoubAshraaf i fixed by adding jcenter()

**Comment by gs-pro-engineer** [comment]
![image](https://user-images.githubusercontent.com/72352483/199990459-0e165834-2dfe-4a91-8a48-77edd23841fe.png)

```
dependencies {
        classpath("com.android.tools.build:gradle:4.1.0")
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'androidx.appcompat:appcompat:1.0.0'
        classpath 'com.facebook.react:react-native:+'
}
```

Who can fix this issue?

**Comment by nikilarigela** [comment]
`Could not determine the dependencies of task ':app:generateBundledResourcesHashDevelopmentDebug'.
> Task with path 'bundleDevelopmentDebugJsAndAssets' not found in project ':app'.`

I Have tried everything from above solution
still not working
Any updates here
