### ISSUE TITLE
install update correctly after app installed,but It always rollback after restart the app

### ISSUE THREAD

**Issue by Mlobaievskyi** [microsoft/react-native-code-push#1725]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Configure coodepush correctly
2. Push update to production branch
3. Immediate update don't work so update on app resume
4. Hard close app and open again

### Expected Behavior
Update from codepush already present

### Actual Behavior
App rolled back to initial state and codepush doesn't apply anymore unless new update uploaded too codepush

### Environment

* react-native-code-push version:  5.7.0
* react-native version: 0.61.4
* iOS/Android/Windows version: iOS 13
* Release
* Physical device (iPhone X, Xs, 11)

**Comment by ahartzog** [comment]
See https://github.com/microsoft/react-native-code-push/issues/1704

There's other similar issues too. I haven't found a solution.

**Comment by chalarlie** [comment]
Having the same issue here.

**Comment by dwilt** [comment]
Same exact issue here.

**Comment by ahartzog** [comment]
@dwilt - try removing the --development flag from your codepush appcenter-cli build command. That resolved the issue for me.

**Comment by Mlobaievskyi** [comment]
@ahartzog I'm not using `--development` flag

**Comment by Mlobaievskyi** [comment]
`code-push release-react <prodIOSBranch> ios -d Production --privateKeyPath ./private.pem --plistFile <pathToPlistFile>`

**Comment by dwilt** [comment]
@ahartzog thanks for the reply, but as @Mlobaievskyi, I'm not using the development flag either

**Comment by ahartzog** [comment]
Ah, must be some other issue going on as well then.

**Comment by sivakumar-cf** [comment]
I am also facing the same issue, I'm not using --development flag. Any update on this issue?

**Comment by luskin** [comment]
removing the `--development` flag fixes the issue of app crashing immediately following update, however this issue (which exists for us as well) is that after a successful update and relaunching of the app it rolls itself back to the previous version.

**Comment by zezest** [comment]
I have same issue, but now it is well then.
this is my solution.

`ios/<app_name>/AppDelegate.m`
```
// add
#import <CodePush/CodePush.h>
```
and change
```
// before
return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];

// after
return [CodePush bundleURL];
```

### Environment
- react-native-code-push version: 5.7.0
- react-native version: 0.61.5
- iOS/Android/Windows version: iOS 13
- Physical device (iPhone Xs Max)

https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native#plugin-configuration-ios

**Comment by luskin** [comment]
@zezest - yes, this will seem to work but if you close the app and then re-open it (don't rebuild) it will revert back to initial bundle. If it is somehow working for you across multiple opens of the app on the same build then good for you, but for the rest of us it reverts.

**Comment by Mlobaievskyi** [comment]
@zezest yes, it work for me also. Not sure when that code was deleted from my app, probably when I upgraded to the new react-native version. I followed back this instructions and it work again https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-ios.md

**Comment by Mlobaievskyi** [comment]
Probably issue not with code-push but with configuration

**Comment by mcruz20** [comment]
Any updates on this?

**Comment by FranciscoSimaoPerez** [comment]
No Updates???? ARE YOU brincating? ME WANT TO WORK AND THIS GUNGA GINGA repository is getting me nuts

**Comment by andreidubov** [comment]
Hi @Mlobaievskyi ,
Thank you for reporting!


As I can see, you are using `react-native v0.61.4` and `react-native-code-push v5.7.0` but these are incompatible versions, you can take a look at supporting CodePush versions here: https://github.com/microsoft/react-native-code-push#supported-react-native-platforms


Not so long ago we released a new version of Code Push which supports react-native v0.60-v0.61. 
All steps for installing the latest version of the plugin are described in our documentation: https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-ios.md

I'm going to close this issue for now. Please let me know if you have any other questions.

**Comment by Saurabh4626** [comment]
this issue is still there? Has anyone figured out a solution

**Comment by DordeDimitrijev** [comment]
Hello @Saurabh4626 thank you for reaching out, could you please tell me which react-native-code-push version and  react-native version are you using?

**Comment by Saurabh4626** [comment]
@DordeDimitrijev, here you go
"react-native": "^0.72.6",
"react-native-code-push": "^8.1.0"

**Comment by DordeDimitrijev** [comment]
@Saurabh4626  Could you try using react-native 0.71.X version since there might be compatability issues with codepush and 0.72 version, and let me know if the issue is still ocurring?

**Comment by DordeDimitrijev** [comment]
Hello @fragilehm thank you for reaching out. I have several questions which can help me further analyze your issue.
- Are you using custom code push server, if so can you try out using default appcenter codepush server?
-  Could you please provide logs from logcat when you apply update to your app?

Ideally it'd be nice if you could share small demo app with me where i can reproduce such behavior.
