### ISSUE TITLE
[iOS] CodePush update lost after restarting the App

### ISSUE THREAD

**Issue by vssalcedo** [microsoft/react-native-code-push#1904]
Hello there.
I’m experiencing a strange behavior when pushing updates with CodePush on iOS Platform.

My binary has the version 2.0. When I make a CodePush update targeting the 2.0 version, the update gets **successfully installed** on device. But when I restart the app (close and open again), it returns to the original binary bundle.

This issue is happening only on iOS, Android is working fine.

### Expected Behavior
After restarting the app, keep the installed codePush version

### Actual Behavior
After restarting the app, i get the old bundle version.

### Scenario

* Using release mode to take the updates from Codepush server instead of the local package server.

* Already replaced this line on AppDelegate.m as the documentation points out: 
```
jsCodeLocation = [CodePush bundleURL];
````
I’m using the JS wrapper this way:

```
let codePushOptions = {
    checkFrequency: codePush.CheckFrequency.ON_APP_START
};

export default UpdatesHandler = codePush(codePushOptions)(UpdatesHandler);
```
And I sync with the codePush server calling the proper method on componentDidMount:
```
componentDidMount() {
codePush.sync({
            updateDialog: false,
            installMode: codePush.InstallMode.IMMEDIATE
 });
}
```

I also tried calling codePush.notifyAppReady() before the sync call but no luck.

I've already checked on mscenter and there are not rollbacks registered. And as you can see here I’m targeting the 2.0 version in all releases: 

![Screenshot](https://user-images.githubusercontent.com/53319615/87422361-ceb81600-c5d8-11ea-83c6-a4ef1ce0d894.png)

### Environment

* react-native-code-push version: 6.2.1
* react-native version: 0.60.5
* iOS/Android/Windows version: iOS 13.3.1
* Does this reproduce on a debug build or release build? Release build
* Does this reproduce on a simulator, or only on a physical device? physical device, haven't tried on simulator yet

**Comment by joshua-davis-rose** [comment]
We experienced the same issue:
react-native-code-push: 6.2.0
react-native: 0.62.2
iOS: 13.5.1

**Comment by ankitsolanki** [comment]
Any updaye on this - same issue on droid.

**Comment by Krasavinigor** [comment]
Hi @vssalcedo!
Thanks for reporting!

Unfortunately, I can't reproduce this issue. Could you please provide a demo app with reproducing issue and reprosteps? I would like to reproduce and investigate this issue.

**Comment by iqfantasysports** [comment]
> We experienced the same issue:
> react-native-code-push: 6.2.0
> react-native: 0.62.2
> iOS: 13.5.1

We're experiencing this same issue. Update is downloaded and applied immediately. Code changes are reflected as expected. On next app start, codepush reverts to running bundle shipped with binary. Please help.

**Comment by iqfantasysports** [comment]
@joshua-davis-rose @vssalcedo Were you able to figure out a solution to this problem? I've had an app running the same manual code sync logic for a couple of years now without issues until recently. Any help is appreciated.

**Comment by vssalcedo** [comment]
Hi @iqfantasysports i've been a little bit busy these days. I tried again but i was not able to solve this problem. I'll try to create a reproducible demo during this week so they can help us with this issue. (If someone could provide his own demo, do it aswell so we can get more feedback).

Btw are u experiencing this issue on both iOS and Android or just iOS?

**Comment by iqfantasysports** [comment]
> Hi @iqfantasysports i've been a little bit busy these days. I tried again but i was not able to solve this problem. I'll try to create a reproducible demo during this week so they can help us with this issue. (If someone could provide his own demo, do it aswell so we can get more feedback).
> 
> Btw are u experiencing this issue on both iOS and Android or just iOS?

@vssalcedo Only on iOS. Android is fine.

**Comment by vssalcedo** [comment]
I tried to create a reproducible demo with the same steps but it works. I ship the new bundle with codepush and after restarting the app i get the updated bundle. 

But when i try the same on my personal project it does not work, idk what is going on. Could someone provide a non-working demo with his own issue?

**Comment by luskin** [comment]
Same issue here! We've tried everything. Everything works as expected until app restarts, then the update gets flagged as a failed install and rolls back. I've confirmed that the app delegate is in fact using the `[CodePush bundleURL]`. We have also tried all variations of notifying codepush that the update was successful and no luck on our end. Hopefully the maintainers will have more information soon.

**Comment by luskin** [comment]
One interesting point to note is that if you simply just wrap your entire application with codepush, it does not roll back:

```typescript
let codePushOptions = {
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
  installMode: codePush.InstallMode.IMMEDIATE,
  mandatoryInstallMode: codePush.InstallMode.IMMEDIATE,
}
export default codePush(codePushOptions)(App)
```

I'm not sure why this works but calling `sync()` when an update is available rolls back but for now this is... "unblocking" us...

**Comment by vssalcedo** [comment]
Hi @luskin Thank you so much for your reply. After hours and hours of researching i finally got this working. 

In my case it was not the code structure itself but a misconfiguration due to incompatibility with other libraries.

For those who are using [React Native Navigation](https://github.com/wix/react-native-navigation) by Wix. Make sure that you are using the proper bundle URL inside the _didFinishLaunchingWithOptions_ method on **AppDelegate.m**:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  
  //NSURL *jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];  
//This was the original setup. So it was grabbing the original bundle instead of the update of the codepush server
  
  NSURL *jsCodeLocation = [CodePush bundleURL]; // Use this when you make the release build
  
  [ReactNativeNavigation bootstrap:jsCodeLocation launchOptions:launchOptions];
  
  [RNSplashScreen show];
  return YES;
}

```
After this change, i was able to successfully download the last update from the Codepush server.

I hope this can help.

**Comment by Krasavinigor** [comment]
Hi @vssalcedo!

I'm going to close this issue for now as It was resolved.
Please feel free to reopen it if you have any questions.

**Comment by mikehuebner** [comment]
Hey all,

Hate to re-open but this is happening to me as well.

Code Push: ^6.3.0
React Native: 0.63.3

Seems that I open the application, on first load the package gets installed no problem. App restarts and then says there no update. Perfect.

I then manually restart the app and the app seems to use the version that was released with the binary, yet my app still shows the latest version when calling `getUpdateMetadata`.

I used some code from @luskin to modify what I had in place for sanity check because what I've been using just stopped. I have other projects this works fine on, not sure what is going on with the latest version.

Here is the hook I wrote using this, feel free to use.

```
const decodeSyncStatus = (status: CodePush.SyncStatus) =>
  Object.entries(CodePush.SyncStatus)
    .filter(([name, value]) => (status === value ? name : ''))
    .reduce(([name, value]) => [String(name), value])[0]

const timeout = (timeoutMS = 10000): Promise<any> =>
  new Promise((_, reject: Function) => {
    const timeoutErr = {
      message: 'Timed out.',
      code: 'ETIMEDOUT'
    }

    setTimeout(reject, timeoutMS, timeoutErr)
  })

const checkForUpdate = async (): Promise<boolean> => {
  try {
    const remotePackage = await CodePush.checkForUpdate()

    logger.log('CodePush Package Recieved:', remotePackage)
    if (remotePackage && !remotePackage?.failedInstall) {
      return true
    }
  } catch (e) {
    logger.error('CodePush Update Failing, `checkForUpdate`', e)
  }

  return false
}

const downloadProgress = ({
  totalBytes,
  receivedBytes
}: {
  totalBytes: number
  receivedBytes: number
}) => {
  logger.log(`Download Progress: ${Math.round((receivedBytes / totalBytes) * 100)}%`)
}

const updateApplication = (): Promise<boolean> => {
  const handleUpdate: Promise<boolean> = new Promise(async (resolve: Function) => {
    const updateAvailable = await checkForUpdate()

    // If we have an update (should be an object) then we should try to apply it via `sync`
    if (updateAvailable) {
      const statusDidChange = (status: CodePush.SyncStatus) => {
        logger.log('CodePush Package Status:', decodeSyncStatus(status))

        switch (status) {
          case CodePush.SyncStatus.UP_TO_DATE:
          case CodePush.SyncStatus.UPDATE_IGNORED:
            console.log('App is up to date...')
            resolve(true)
            break
          case CodePush.SyncStatus.UPDATE_INSTALLED:
            console.log('Update installed successfully!')
            // DO NOT RESOLVE AS THE APP WILL REBOOT ITSELF HERE
            break
          case CodePush.SyncStatus.UNKNOWN_ERROR:
            console.log('Update received an unknown error...')
            resolve(true)
            break
          default:
            break
        }
      }

      // Sync with CodePush
      CodePush.sync(
        {
          installMode: CodePush.InstallMode.IMMEDIATE,
          mandatoryInstallMode: CodePush.InstallMode.IMMEDIATE
        },
        statusDidChange
      )
    } else {
      logger.log('No CodePush Update Available...')
      resolve(true)
    }
  })

  // Give it a max of 5 seconds to get the update in order, we don't want to leave the user hanging for much longer.
  return Promise.race([handleUpdate, timeout(5000)])
}

export const useCodePushSync = () => {
  const [codePushIsSynced, setSyncStatus] = useState(false)

  useEffect(() => {
    const handleUpdate = async () => {
      try {
        await updateApplication()
      } catch (e) {
        logger.error(e)
      }

      // Regardless of what happens, we need to push the user into the app...
      setSyncStatus(true)
    }

    handleUpdate()
  }, [])

  return codePushIsSynced
}
```

**Comment by tuanphamanh91** [comment]
> Hi @luskin Thank you so much for your reply. After hours and hours of researching i finally got this working.
> 
> In my case it was not the code structure itself but a misconfiguration due to incompatibility with other libraries.
> 
> For those who are using [React Native Navigation](https://github.com/wix/react-native-navigation) by Wix. Make sure that you are using the proper bundle URL inside the _didFinishLaunchingWithOptions_ method on **AppDelegate.m**:
> 
> ```
> - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> {
>   
>   //NSURL *jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];  
> //This was the original setup. So it was grabbing the original bundle instead of the update of the codepush server
>   
>   NSURL *jsCodeLocation = [CodePush bundleURL]; // Use this when you make the release build
>   
>   [ReactNativeNavigation bootstrap:jsCodeLocation launchOptions:launchOptions];
>   
>   [RNSplashScreen show];
>   return YES;
> }
> ```
> 
> After this change, i was able to successfully download the last update from the Codepush server.
> 
> I hope this can help.

I implement this and it worked okay a few days. But today I continue this bug happen

**Comment by SnidelyWhiplash** [comment]
@luskin's [answer](https://github.com/microsoft/react-native-code-push/issues/1904#issuecomment-670960745) saved me. Even if you're handling all the CP logic yourself, like via a modal/button, you still need to wrap your main App component with codePush with a `manual` check flag. Without this, updates will rollback upon next app boot.

```js
@codePush({
  checkFrequency: codePush.CheckFrequency.MANUAL,
})
export default class App extends Component {
  // ...
}
```

**Comment by antoinedelp** [comment]
We are experiencing the same issue on iOs, Android works fine. Our app manages to fetch and download the lastest CodePush bundle, but once the app is rebooted it reverts back to the binary version. 
 We wrap our app with codePush, we checked thatwe have the correct bundle JS location. We do not call sync though.

```
const codePushOptions = {
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
  installMode: codePush.InstallMode.ON_NEXT_RESUME,
  minimumBackgroundDuration: 60
}

if (!__DEV__) {
  App = codePush(codePushOptions)(App)
} else {
  console.log("Code Push has been disabled in development.")
}
export default App
```

**Comment by neildevas** [comment]
Still experiencing this issue on iOS with react-native code-push, even after using @luskin solution

**Comment by ktt9117** [comment]
```
"react-native": "0.61.5",
"react-native-code-push": "^6.4.0",
```
We experienced the same issue. This only happens on iOS where I have configured the build schema to releaseStaging.
Is there any solution?

**Comment by girish54321** [comment]
Noting is working for me iOS app not saving updates after restarting the App and the dashboard shows 0 Downloads.

<img width="699" alt="Screenshot 2021-07-08 at 8 14 45 PM" src="https://user-images.githubusercontent.com/47414322/124942744-84ba1280-e029-11eb-88ee-4afb4d9fb100.png">

.

**Comment by ZaharGusyatin** [comment]
any updates?

**Comment by anhht2-fabbi** [comment]
same issue because i forgot replace "return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"]" to return [CodePush bundleURL]

**Comment by anhquan291** [comment]
Hi guys, I'm facing the same issue on iOS
I'm using:
` "react-native": "0.68.2",
"react-native-code-push": "^7.0.5",
`
`
  useEffect(() => {
    if (isLoadingComplete) {
      CodePush.sync({
        deploymentKey:
          Platform.OS === 'ios'
            ? appConfigs?.CODE_PUSH_KEY_IOS
            : appConfigs?.CODE_PUSH_KEY_ANDROID,
        updateDialog: false,
        installMode: CodePush.InstallMode.IMMEDIATE,
      });
    }
  }, [isLoadingComplete]);
`
I'm sure that I setup the project correctly since everything is working perfectly on another project that uses `"react-native": "0.67.4"`. Thank you guys. Really appreciate it.

**Comment by SutharRohit** [comment]
Hi,

I am getting the same issue in iOS only, but for the android it is working fine.

i am using:
```
"react-native": "0.66.4",
"react-native-code-push": "^7.1.0",
```

tried all the above solutions, but did not get success.

**Comment by akhilsanker** [comment]
Hi @vssalcedo,

Did it works for you?. I'm still facing the issue. Works fine in Android but issues in iOS.

```
"react-native": "0.71.14",
"react-native-code-push": "8.0.0"

Xcode: Version 15.4 
```

Thanks
